name: Static Site Generation from Remix with wget

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    
    - name: Cache dependancies
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
            ${{ runner.os }}-yarn-
            
    - name: Install dependencies
      run: yarn
      
    - name: Build
      run: yarn build
      
    - name: Start server and mirror it with wget
      run: |
            yarn start &
            sleep 10 &&
            wget --mirror http://localhost:3000 -P out --no-host-directories --page-requisites --adjust-extension
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./out