name: Building Website Artifacts

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x]

    steps:
    - uses: actions/checkout@v1

    - name: Using Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: yarn install

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3


